export const GETTING_INSTRUMENTS = 'GETTING_INSTRUMENTS';
export const GETTING_INSTRUMENTS_SUCCESS = 'GETTING_INSTRUMENTS_SUCCESS';
export const GETTING_INSTRUMENTS_FAILURE = 'GETTING_INSTRUMENTS_FAILURE';