export const GETTING_INSTRUMENTS = 'GETTING_INSTRUMENTS';
export const GETTING_INSTRUMENTS_SUCCESS = 'GETTING_INSTRUMENTS_SUCCESS';
export const GETTING_INSTRUMENTS_FAILURE = 'GETTING_INSTRUMENTS_FAILURE';
export const GETTING_ACCOUNT = 'GETTING_ACCOUNT';
export const GETTING_ACCOUNT_SUCCESS = 'GETTING_ACCOUNT_SUCCESS';
export const GETTING_ACCOUNT_FAILURE = 'GETTING_ACCOUNT_FAILURE';